name: cppcheck

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ci-cppcheck
    if: ${{ github.repository != 'intel/pcm' }}        

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: cppcheck_script
      run: |
        sh ${{ github.workspace }}/scripts/cppcheck.sh . `getconf _NPROCESSORS_ONLN`
