name: coverity-windows

on: [workflow_dispatch, workflow_call]

jobs:
  build:

    runs-on: ci-kw-windows
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: coverity-windows
      run: |
        mkdir build
        cd build
        cmake ..
        c:\pcm\ci-cov-windows.ps1

    - name: coverity-windows-cs
      run: |
        mkdir build-cs
        cd build-cs
        cmake ..
        c:\pcm\ci-cov-windows-cs.ps1

    - name: coverity-windows-msr
      run: |
        chdir ${{github.workspace}}\src\WinMSRDriver
        c:\pcm\ci-cov-windows-msr.ps1

    - name: coverity-windows-report
      run: |
        c:\pcm\ci-cov-windows-report.ps1 PCM.windows-all

    - name: upload-artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: coverity-windows-all-report-${{ github.sha }}
        path: "*-Report.pdf"
