name: stats-cron-job

on:
  schedule:
    - cron: '30 23 * * 2'

jobs:
  stats:
    runs-on: ubuntu-20.04
    steps:
    - name: stats
      run: |
        curl https://hetthbszh0.execute-api.us-east-2.amazonaws.com/default/pcm-clones
